### ISSUE TITLE
How to make screenshoot

### ISSUE THREAD

**Issue by CatTalk2** [kinneyyan/36krReader#1]
问一个很低级的问题，你是怎么做出这种截屏效果的....动态内容没法预览

**Comment by kinneyyan** [comment]
android studio中的截图，有带壳截图的选项

**Comment by CatTalk2** [comment]
预览的时候，这些动态的东西不会被加载啊，主要里面内容怎么截进去的，你用的Mac？

在 2015-10-30 14:27:52，"yanshi" notifications@github.com 写道：

android studio中的截图，有带壳截图的选项

**Comment by kinneyyan** [comment]
跟平台无关啊。手机adb连接后，android studio中的截图可以截取当前手机展示的界面啊。
<img width="770" alt="2015-10-30 14 38 27" src="https://cloud.githubusercontent.com/assets/10083989/10839920/5b91e3e6-7f14-11e5-8550-2089829ef247.png">

**Comment by CatTalk2** [comment]
Nice，知道了，非常感谢
