### ISSUE TITLE
关于 CardView 风格的改进

### ISSUE THREAD

**Issue by fython** [kinneyyan/36krReader#2]
很荣幸我的文章能成为你在 CardView 方面的小参考，由于时间有限我在里面写的大多只是一些规范性的问题。
实际上 CardView 还有一种设计用法就是水平方向（左右）与屏幕贴边，像 Lollipop 的系统设置列表那样，这种设计很适合做一些带 Sub Header 的列表。

如果这种设计你也觉得不错的话可以试一试，效果肯定很棒ww

**Comment by kinneyyan** [comment]
好的，非常感谢😊
